#!/bin/bash
# ClariceOS — Limine bootloader installer
# Runs inside the target system chroot via Calamares shellprocess.
#
# Features:
#   - Installs Limine for BIOS or UEFI
#   - Generates limine.cfg with kernel + fallback entries
#   - If root filesystem is btrfs: sets up snapper + limine-snapper-sync
#     so every snapper snapshot gets a boot entry automatically

set -euo pipefail

# ── Detect environment ────────────────────────────────────────────────────────

ROOT_UUID=$(findmnt -n -o UUID / 2>/dev/null)
ROOT_DEVICE=$(findmnt -n -o SOURCE /)
ROOT_FS=$(findmnt -n -o FSTYPE /)

# Resolve the physical disk backing a mounted source. This handles mapper/LVM
# devices by walking parent block devices until reaching the top-level disk.
resolve_disk() {
    local src="$1"
    local parent=""


    while true; do
        parent=$(lsblk -no PKNAME "${src}" 2>/dev/null | head -1 || true)
        [ -z "${parent}" ] && break
        [ -b "/dev/${parent}" ] || break
        src="/dev/${parent}"
    done

    basename "${src}"
}


if [ -z "${ROOT_UUID}" ]; then
    echo "ERROR: Could not determine root partition UUID. Aborting bootloader install."
    exit 1
fi
if [ -z "${ROOT_DEVICE}" ]; then
    echo "ERROR: Could not determine root device. Aborting bootloader install."
    exit 1
fi

# Physical disk that backs the root device (e.g. /dev/nvme0n1 from /dev/nvme0n1p2
# or from mapper/LVM roots).
DISK=$(resolve_disk "${ROOT_DEVICE}" || true)
if [ -z "${DISK}" ] || [ ! -b "/dev/${DISK}" ]; then
    echo "ERROR: Could not resolve target disk from root device '${ROOT_DEVICE}'."
    exit 1
fi

# UEFI: efivarfs is bind-mounted into the chroot by Calamares mount.conf
UEFI=false
[ -d /sys/firmware/efi/efivars ] && UEFI=true

# btrfs: check root filesystem type
BTRFS=false
[ "${ROOT_FS}" = "btrfs" ] && BTRFS=true

echo "==> Limine install: UEFI=${UEFI}  btrfs=${BTRFS}"
echo "    root device : ${ROOT_DEVICE}  (UUID=${ROOT_UUID})"
echo "    disk        : /dev/${DISK}"

# ── Build CMDLINE ─────────────────────────────────────────────────────────────

CMDLINE="root=UUID=${ROOT_UUID} rw quiet splash lsm=landlock,lockdown,yama,integrity,apparmor,bpf"

if ${BTRFS}; then
    # Extract the subvolume from current mount options (set by Calamares fstab)
    # Uses POSIX grep+sed instead of grep -P (Perl regex) for portability.
    BTRFS_SUBVOL=$(findmnt -n -o OPTIONS / | grep -o 'subvol=[^,]*' | sed 's/subvol=//' || true)
    [ -z "${BTRFS_SUBVOL}" ] && BTRFS_SUBVOL="@"
    CMDLINE="${CMDLINE} rootflags=subvol=${BTRFS_SUBVOL}"
    echo "    btrfs subvol: ${BTRFS_SUBVOL}"
fi

# ── Write limine.cfg ──────────────────────────────────────────────────────────
# UEFI : config lives on the ESP so Limine EFI can read it at firmware time.
#        Kernel/initramfs are on the root partition referenced by UUID.
# BIOS : config lives at /boot on the root partition.  boot:// refers to the
#        partition root (not /boot/), so paths must include /boot explicitly.

write_limine_cfg() {
    local cfg_path="$1"
    local kernel_prefix="$2"   # "uuid://${ROOT_UUID}/boot" or "boot:///boot"
    local initrd_prefix="$3"

    mkdir -p "$(dirname "${cfg_path}")"
    cat > "${cfg_path}" << CFG
# ClariceOS Limine configuration
# Generated by ClariceOS installer — do not edit manually.
# Managed by limine-snapper-sync when btrfs+snapper is active.

TIMEOUT=5
GRAPHICS=yes
DEFAULT_ENTRY=1
INTERFACE_BRANDING=ClariceOS

:ClariceOS Linux
    COMMENT=ClariceOS (linux)
    PROTOCOL=linux
    KERNEL_PATH=${kernel_prefix}/vmlinuz-linux
    CMDLINE=${CMDLINE}
    MODULE_PATH=${initrd_prefix}/initramfs-linux.img

:ClariceOS Linux (fallback initramfs)
    COMMENT=ClariceOS (linux, fallback)
    PROTOCOL=linux
    KERNEL_PATH=${kernel_prefix}/vmlinuz-linux
    CMDLINE=${CMDLINE}
    MODULE_PATH=${initrd_prefix}/initramfs-linux-fallback.img
CFG

    # linux-zen entries — appended only if the kernel is present
    if [ -f "/boot/vmlinuz-linux-zen" ]; then
        cat >> "${cfg_path}" << CFG_ZEN

:ClariceOS Linux Zen
    COMMENT=ClariceOS (linux-zen, low-latency)
    PROTOCOL=linux
    KERNEL_PATH=${kernel_prefix}/vmlinuz-linux-zen
    CMDLINE=${CMDLINE}
    MODULE_PATH=${initrd_prefix}/initramfs-linux-zen.img

:ClariceOS Linux Zen (fallback initramfs)
    COMMENT=ClariceOS (linux-zen, fallback)
    PROTOCOL=linux
    KERNEL_PATH=${kernel_prefix}/vmlinuz-linux-zen
    CMDLINE=${CMDLINE}
    MODULE_PATH=${initrd_prefix}/initramfs-linux-zen-fallback.img
CFG_ZEN
        echo "    linux-zen entries added to limine.cfg."
    fi

    echo "    limine.cfg written → ${cfg_path}"
}

# Detect ESP mount point: try /boot/efi, /boot, /efi in order.
detect_esp() {
    for mp in /boot/efi /boot /efi; do
        local t
        local fs
        t=$(findmnt -n -o TARGET "${mp}" 2>/dev/null)
        fs=$(findmnt -n -o FSTYPE "${mp}" 2>/dev/null || true)
        if [ -n "${t}" ] && mountpoint -q "${t}" && \
           echo "${fs}" | grep -qiE 'vfat|fat|msdos'; then
            echo "${t}"
            return 0
        fi
    done
    return 1
}

if ${UEFI}; then
    if ! ESP=$(detect_esp); then
        echo "ERROR: UEFI mode detected but no mounted FAT ESP was found."
        echo "       Expected one of: /boot/efi, /boot or /efi (FAT filesystem)."
        exit 1
    fi
    echo "    ESP detected at: ${ESP}"
    K_PREFIX="uuid://${ROOT_UUID}/boot"
    write_limine_cfg "${ESP}/limine.cfg"        "${K_PREFIX}" "${K_PREFIX}"
    write_limine_cfg "/boot/limine.cfg"          "${K_PREFIX}" "${K_PREFIX}"
else
    # /boot lives inside the root partition (typical BIOS layout — no separate
    # /boot partition).  Limine's boot:// refers to the partition root, so
    # all kernel/initramfs paths must include the /boot prefix.
    write_limine_cfg "/boot/limine.cfg" "boot:///boot" "boot:///boot"
fi

# ── Install Limine ────────────────────────────────────────────────────────────

if ${UEFI}; then
    # Reuse the validated ESP found above instead of resolving again.
    : "${ESP:?missing ESP mount point}"

    mkdir -p "${ESP}/EFI/limine" "${ESP}/EFI/BOOT"

    # Limine EFI binary (64-bit)
    cp /usr/share/limine/BOOTX64.EFI "${ESP}/EFI/limine/"
    # Fallback path — firmware will boot this if no NVRAM entry is found
    cp /usr/share/limine/BOOTX64.EFI "${ESP}/EFI/BOOT/"

    echo "    Limine EFI binaries copied."

    # Register a firmware boot entry via efibootmgr
    if command -v efibootmgr &>/dev/null; then
        # Register entry against the disk that actually backs the ESP.
        EFI_DEVICE=$(findmnt -n -o SOURCE "${ESP}" 2>/dev/null || true)
        EFI_DISK=$(resolve_disk "${EFI_DEVICE}" || true)
        EFI_PART_NUM=$(lsblk -no PARTN "${EFI_DEVICE}" 2>/dev/null | head -1 || echo "1")
        [ -z "${EFI_PART_NUM}" ] && EFI_PART_NUM="1"
        if [ -n "${EFI_DISK}" ] && [ -b "/dev/${EFI_DISK}" ]; then
            efibootmgr --create \
                --disk "/dev/${EFI_DISK}" \
                --part "${EFI_PART_NUM}" \
                --label "ClariceOS (Limine)" \
                --loader "/EFI/limine/BOOTX64.EFI" \
                2>/dev/null \
                && echo "    UEFI boot entry created." \
                || echo "    WARNING: efibootmgr failed — EFI/BOOT fallback will be used."
        else
            echo "    WARNING: could not resolve ESP disk for efibootmgr; EFI/BOOT fallback will be used."
        fi
    fi
else
    # BIOS: write Limine to the MBR of the target disk
    if [ -z "${DISK}" ]; then
        echo "ERROR: could not determine target disk — cannot install Limine (BIOS)."
        exit 1
    fi
    # limine-bios.sys must exist on disk BEFORE bios-install so it can embed
    # the correct sector pointers into the MBR code.
    cp /usr/share/limine/limine-bios.sys /boot/
    limine bios-install "/dev/${DISK}"
    echo "    Limine installed to MBR of /dev/${DISK}."
fi

echo "==> Limine installed successfully."

# ── btrfs + snapper + limine-snapper-sync ────────────────────────────────────

if ! ${BTRFS}; then
    echo "==> Root is not btrfs — skipping snapshot setup."
    exit 0
fi

echo "==> btrfs detected — configuring snapper + limine-snapper-sync..."

# snapper and snap-pac are already installed via packages.x86_64.
# Create the root snapshot configuration.
if ! snapper -c root list &>/dev/null 2>&1; then
    snapper -c root create-config /
    echo "    snapper root config created."
fi

# Enable snapper automatic timeline + cleanup timers
systemctl enable snapper-timeline.timer 2>/dev/null || true
systemctl enable snapper-cleanup.timer  2>/dev/null || true

# snap-pac creates pre/post snapshots around pacman transactions automatically
# (already installed; no extra config needed)
echo "    snapper timers enabled, snap-pac active."

# ── limine-snapper-sync ───────────────────────────────────────────────────────
# This AUR package watches /.snapshots/ and regenerates limine.cfg entries
# for every snapper snapshot, enabling rollback from the boot menu.

install_limine_snapper_sync() {
    echo "    Attempting to install limine-snapper-sync from AUR..."

    # Requires git and base-devel in the installed system
    pacman -S --noconfirm --needed git base-devel 2>/dev/null || {
        echo "    WARNING: git/base-devel unavailable — cannot build from AUR."
        return 1
    }

    # Create an unprivileged build user (makepkg refuses to run as root)
    useradd -m -G wheel _build 2>/dev/null || true
    echo "_build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/99-build-user

    local BUILD_DIR
    BUILD_DIR=$(mktemp -d)
    # Ensure BUILD_DIR and the _build user are always cleaned up, even on error.
    trap "rm -rf '${BUILD_DIR}'; rm -f /etc/sudoers.d/99-build-user; userdel -r _build 2>/dev/null || true" RETURN
    chown -R _build:_build "${BUILD_DIR}"

    sudo -u _build bash -c "
        git clone https://aur.archlinux.org/limine-snapper-sync.git '${BUILD_DIR}/pkg'
        cd '${BUILD_DIR}/pkg'
        makepkg -si --noconfirm
    " && echo "    limine-snapper-sync installed from AUR." \
      || { echo "    WARNING: AUR build failed."; return 1; }
}

if pacman -Q limine-snapper-sync &>/dev/null 2>&1; then
    echo "    limine-snapper-sync already installed."
else
    install_limine_snapper_sync || true
fi

# Enable limine-snapper-sync if successfully installed
if pacman -Q limine-snapper-sync &>/dev/null 2>&1; then
    # Configure the path to limine.cfg (differs for UEFI vs BIOS)
    mkdir -p /etc/limine-snapper-sync
    if ${UEFI}; then
        ESP=$(detect_esp)
        cat > /etc/limine-snapper-sync/config << LSS_CONF
LIMINE_CFG="${ESP}/limine.cfg"
LIMINE_BIOS_INSTALL=""
ROOT_UUID="${ROOT_UUID}"
LSS_CONF
    else
        cat > /etc/limine-snapper-sync/config << LSS_CONF
LIMINE_CFG="/boot/limine.cfg"
LIMINE_BIOS_INSTALL="/dev/${DISK}"
ROOT_UUID="${ROOT_UUID}"
LSS_CONF
    fi

    # Enable the path watcher — fires whenever /.snapshots/ changes
    systemctl enable limine-snapper-sync.path 2>/dev/null \
        && echo "    limine-snapper-sync.path enabled." \
        || echo "    WARNING: limine-snapper-sync service not found."
else
    echo "    limine-snapper-sync not available."
    echo "    Snapshots will be created by snapper but won't appear as boot entries."
    echo "    Install 'limine-snapper-sync' from AUR after first boot to enable this."
fi

echo "==> btrfs/snapper setup complete."
