---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - netinstall@profile
    - netinstall@desktop
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopenswaphookcfg
    - shellprocess@remove-live-pkgs
    - netinstall@profile
    - netinstall@desktop
    - shellprocess@btrfshooks
    - shellprocess@mkinitcpio
    - shellprocess@bootloader
    - removeuser
    - hwclock
    - services-systemd
    - users
    - shellprocess
    - shellprocess@secureboot
    - networkcfg
    - shellprocess@limine-deploy
    - umount
  - show:
    - finished

branding: clariceos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
